[package]
name = "objects"
authors = ["Junon", "Antonin Hérault <antonherault@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
x64asm = { git = "https://github.com/antoninhrlt/x64asm" }